name: Deploy GH Pages

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: false
        default: 'main'
        type: string

env:
  CARGO_TERM_COLOR: always
  TRUNK_VERSION: "v0.21.14"

jobs:
  deploy_docs:
    name: Deploy site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "wasm32-unknown-unknown"

      - name: Install Trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/${TRUNK_VERSION}/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build site
        run: ./trunk build --release

      - name: Finalize dist directory
        run: |
          touch dist/.nojekyll
          echo -n "${{ vars.CNAME }}" > dist/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
